# Generated by Django 5.1.6 on 2025-02-16 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cpcprofile_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='additional_info',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to='cover_letters/'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.student'),
        ),
    ]
