# Generated by Django 5.1.6 on 2025-02-15 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_college_jobdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPCProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('major_field', models.CharField(help_text='E.g. Tech, Engineering, Business, Medicine', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cpc_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
