# Generated by Django 5.1.6 on 2025-02-16 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_jobapplication_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendedApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(help_text='Percentage match between application and job requirements (0-100)')),
                ('skills_matched', models.JSONField(help_text='List of skills that match job requirements')),
                ('qualification_score', models.FloatField(help_text='Score for educational qualifications match')),
                ('experience_score', models.FloatField(help_text='Score for relevant experience match')),
                ('ai_feedback', models.TextField(help_text='AI analysis and recommendation notes')),
                ('is_recommended', models.BooleanField(default=False, help_text='Final AI recommendation decision')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendation', to='core.jobapplication')),
            ],
            options={
                'verbose_name': 'AI Recommended Application',
                'verbose_name_plural': 'AI Recommended Applications',
                'ordering': ['-match_score'],
            },
        ),
    ]
