# Generated by Django 5.1.6 on 2025-02-17 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_airecommendedapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIRecommendedApplication',
        ),
    ]
