# Generated by Django 5.1.6 on 2025-02-17 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_airecommendedapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='student',
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='benefits',
            field=models.TextField(blank=True, help_text='List job benefits and perks'),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='job_category',
            field=models.CharField(blank=True, choices=[('tech', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='location_type',
            field=models.CharField(blank=True, choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site')], default='onsite', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='pay_grade',
            field=models.CharField(blank=True, choices=[('entry', 'Entry Level (0-2 years)'), ('junior', 'Junior Level (2-4 years)'), ('mid', 'Mid Level (4-6 years)'), ('senior', 'Senior Level (6+ years)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='salary_range',
            field=models.CharField(blank=True, help_text='e.g., $50,000 - $70,000', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='skills_required',
            field=models.TextField(blank=True, help_text='List key skills required for this position', null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='work_location',
            field=models.CharField(blank=True, help_text='City, Country or Remote', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='industry',
            field=models.CharField(blank=True, choices=[('tech', 'Technology'), ('finance', 'Finance'), ('health', 'Healthcare'), ('education', 'Education'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='college',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cpcprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cpcprofile',
            name='major_field',
            field=models.CharField(blank=True, help_text='E.g. Tech, Engineering, Business, Medicine', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cpcprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpc_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.jobdescription'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_descriptions', to='core.businessprofile'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='required_qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('business_admin', 'Business Admin'), ('cpc_admin', 'CPC Admin')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='CustomQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(blank=True, null=True)),
                ('question_type', models.CharField(blank=True, choices=[('text', 'Text Answer'), ('multiple_choice', 'Multiple Choice'), ('yes_no', 'Yes/No'), ('file_upload', 'File Upload')], max_length=20, null=True)),
                ('is_required', models.BooleanField(blank=True, default=True, null=True)),
                ('options', models.JSONField(blank=True, help_text='For multiple choice questions, provide options as a JSON array', null=True)),
                ('order', models.IntegerField(blank=True, default=0, help_text='Order in which questions should appear', null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_questions', to='core.jobdescription')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True, null=True)),
                ('file_response', models.FileField(blank=True, null=True, upload_to='question_responses/')),
                ('job_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='core.jobapplication')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customquestion')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('education_level', models.CharField(blank=True, choices=[('undergraduate', 'Undergraduate'), ('graduate', 'Graduate'), ('postgraduate', 'Post Graduate')], max_length=50, null=True)),
                ('course', models.CharField(blank=True, max_length=255, null=True)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, help_text='List your key skills', null=True)),
                ('bio', models.TextField(blank=True)),
                ('linkedin_profile', models.URLField(blank=True)),
                ('github_profile', models.URLField(blank=True)),
                ('portfolio_website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cpc_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cpcprofile')),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
            },
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='student_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.studentprofile'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
