# Generated by Django 5.1.6 on 2025-02-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_jobapplication_student_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobdescription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Job Description', 'verbose_name_plural': 'Job Descriptions'},
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='benefits',
            field=models.TextField(blank=True, help_text='List job benefits and perks', null=True),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
