# Generated by Django 5.1.6 on 2025-02-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_jobdescription_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customquestion',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='customquestion',
            name='order',
        ),
        migrations.AddField(
            model_name='customquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
