# Generated by Django 5.1.6 on 2025-02-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_studentprofile_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], max_length=20, null=True),
        ),
    ]
